
IF OBJECT_ID('tempdb..#SD2_NFS') IS NOT NULL DROP TABLE #SD2_NFS

SELECT * INTO #SD2_NFS FROM (
SELECT DISTINCT D2_DOC, D2_FILIAL, D2_SERIE, D2_TIPO, F4_ESTOQUE
, ISNULL(A2_COD,A1_COD) CLIFOR_COD, ISNULL(A2_LOJA,A1_LOJA) CLIFOR_LOJA, ISNULL(A2_NREDUZ + '  ',A1_NREDUZ) CLIFOR_NREDUZ, ISNULL(A2_NOME,A1_NOME) CLIFOR_NOME
FROM SD2010 SD2
LEFT JOIN SF4010 SF4 ON F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA1010 SA1 ON A1_COD = D2_CLIENTE AND A1_LOJA = D2_LOJA AND SA1.D_E_L_E_T_ <> '*' AND NOT D2_TIPO IN ('B','D')
LEFT JOIN SA2010 SA2 ON A2_COD = D2_CLIENTE AND A2_LOJA = D2_LOJA AND SA2.D_E_L_E_T_ <> '*' AND D2_TIPO IN ('B','D')
WHERE SD2.D_E_L_E_T_ <> '*') t

IF OBJECT_ID('tempdb..#SD1_NFS') IS NOT NULL DROP TABLE #SD1_NFS
SELECT * INTO #SD1_NFS FROM (
SELECT TOP 1 WITH TIES D1_DOC, D1_FILIAL, D1_SERIE, D1_TIPO, F4_ESTOQUE
, ISNULL(A2_COD,A1_COD) CLIFOR_COD, ISNULL(A2_LOJA,A1_LOJA) CLIFOR_LOJA, ISNULL(A2_NREDUZ + '  ', A1_NREDUZ) CLIFOR_NREDUZ, ISNULL(A2_NOME,A1_NOME) CLIFOR_NOME
FROM SD1010 SD1
LEFT JOIN SF4010 SF4 ON F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA2010 SA2 ON A2_COD = D1_FORNECE AND A2_LOJA = D1_LOJA AND SA2.D_E_L_E_T_ <> '*' AND NOT D1_TIPO IN ('B','D')
LEFT JOIN SA1010 SA1 ON A1_COD = D1_FORNECE AND A1_LOJA = D1_LOJA AND SA1.D_E_L_E_T_ <> '*' AND D1_TIPO IN ('B','D')
WHERE SD1.D_E_L_E_T_ <> '*'
ORDER BY ROW_NUMBER() OVER(PARTITION BY D1_DOC, D1_FILIAL, A2_COD, A1_COD, A2_LOJA, A1_LOJA ORDER BY D1_DOC, D1_FILIAL, D1_SERIE, D1_TIPO, A2_LOJA, A1_LOJA )) u

SELECT * FROM (

SELECT 'SD1' AS TABELA, D1_FILIAL FILIAL, D1_LOCAL ESTOQUE, D1_XSERIAL SERIAL,B1_COD PROD, B1_DESC DESCR, CTD_DESC01 LINHA,
SUBSTRING(D1_DTDIGIT,7,2) + '/' + SUBSTRING(D1_DTDIGIT,5,2) + '/' + SUBSTRING(D1_DTDIGIT,1,4) DT,
TRIM(D1_LOTECTL) LOTE, D1_DOC DOC, D1_SERIE, D1_TES TES, F4_TEXTO DESC_MOV, D1_CF CF
,'E' AS TIPO_MOV,
SUM(D1_QUANT) QUANT, D1_IDENTB6 IDENT, D1_PEDIDO PEDIDO, D1_TIPO TIPO, F4_ESTOQUE MOV_ESTOQUE
, ISNULL(A1_COD, A2_COD) CLIFOR_COD
, ISNULL(A1_LOJA, A2_LOJA) CLIFOR_LOJA
, ISNULL(A2_NREDUZ + '  ', A1_NREDUZ) CLIFOR_NREDUZ
, ISNULL(A1_NOME, A2_NOME) CLIFOR_NOME
FROM SD1010 SD1
LEFT JOIN SB1010 SB1 ON
B1_COD = D1_COD AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN SF4010 SF4 ON
SF4.F4_CODIGO = SD1.D1_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA2010 SA2 ON A2_COD = D1_FORNECE AND A2_LOJA = D1_LOJA AND SA2.D_E_L_E_T_ <> '*' AND NOT D1_TIPO IN ('B','D')
LEFT JOIN SA1010 SA1 ON A1_COD = D1_FORNECE AND A1_LOJA = D1_LOJA AND SA1.D_E_L_E_T_ <> '*' AND D1_TIPO IN ('B','D')
WHERE SD1.D_E_L_E_T_ <> '*'
AND B1_TIPO = 'PA'
--AND D1_DTDIGIT >= '20211206'
GROUP BY D1_FILIAL, D1_LOCAL, B1_COD, B1_DESC, CTD_DESC01, D1_LOTECTL, D1_CF, D1_DTDIGIT, D1_DOC, D1_TES, D1_SERIE, D1_IDENTB6, D1_PEDIDO, F4_TEXTO, D1_TIPO, F4_ESTOQUE
, A1_COD, A2_COD, A1_LOJA, A2_LOJA, A1_NREDUZ, A2_NREDUZ, A1_NOME, A2_NOME, D1_XSERIAL

union all

SELECT 'SD2' AS TABELA,D2_FILIAL FILIAL, D2_LOCAL ESTOQUE, D2_NUMSERI,B1_COD CODIGO, B1_DESC DESCRICAO, CTD_DESC01 LINHA,
SUBSTRING(D2_EMISSAO,7,2) + '/' + SUBSTRING(D2_EMISSAO,5,2) + '/' + SUBSTRING(D2_EMISSAO,1,4) DT,
TRIM(D2_LOTECTL) LOTE, D2_DOC NF, D2_SERIE SERIE, D2_TES TES, F4_TEXTO DESC_MOV, D2_CF CF, 'S' AS [TIPO], SUM(D2_QUANT) * -1 QUANT, D2_IDENTB6 IDENT, D2_PEDIDO PEDIDO,  D2_TIPO TIPO_NF, F4_ESTOQUE MOV_ESTOQUE
, ISNULL(A1_COD, A2_COD) CLIFOR_COD
, ISNULL(A1_LOJA, A2_LOJA) CLIFOR_LOJA
, ISNULL(A2_NREDUZ + '  ', A1_NREDUZ) CLIFOR_NREDUZ
, ISNULL(A1_NOME, A2_NOME) CLIFOR_NOME
FROM SD2010 SD2
LEFT JOIN SB1010 SB1 ON
B1_COD = D2_COD AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN SF4010 SF4 ON
SF4.F4_CODIGO = SD2.D2_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA1010 SA1 ON A1_COD = D2_CLIENTE AND A1_LOJA = D2_LOJA AND SA1.D_E_L_E_T_ <> '*' AND NOT D2_TIPO IN ('B','D')
LEFT JOIN SA2010 SA2 ON A2_COD = D2_CLIENTE AND A2_LOJA = D2_LOJA AND SA2.D_E_L_E_T_ <> '*' AND D2_TIPO IN ('B','D')
WHERE SD2.D_E_L_E_T_ <> '*' AND B1_TIPO = 'PA'
--AND D2_EMISSAO >= '20211206'
GROUP BY D2_FILIAL, D2_LOCAL, B1_COD, B1_DESC, CTD_DESC01, D2_LOTECTL, D2_CF, D2_EMISSAO, D2_DOC, D2_TES, D2_SERIE, D2_IDENTB6, D2_PEDIDO, F4_TEXTO, D2_TIPO, F4_ESTOQUE
, A1_COD, A2_COD, A1_LOJA, A2_LOJA, A1_NREDUZ, A2_NREDUZ, A1_NOME, A2_NOME, D2_NUMSERI

UNION ALL

SELECT 'SBF' AS TAB
	, BF_FILIAL FILIAL
	, BF_LOCAL ESTOQUE
	, BF_NUMSERI
	, B1_COD CODIGO
	, B1_DESC DESCRICAO
	, CTD_DESC01 LINHA
	, CAST(DAY(GETDATE()) AS VARCHAR(50)) + '/' + CAST(MONTH(GETDATE()) AS nvarchar(50)) + '/' +  CAST(YEAR(GETDATE()) AS nvarchar(50)) DT
	,BF_LOTECTL
	, 'DOC' AS DOC
	, 'DOCSERI' AS DOCSERIE
	, 'TES' AS TES
	, 'F4_TEXTO' AS F4_TEXTO
	, 'CF' AS CF
	, 'EST' AS [TIPO]
	, (BF_QUANT)
	, 'IDENT' AS IDENT
	, 'PEDIDO' AS PEDIDO
	, 'D2_TIPO' AS TIPO_NF
	, 'F4_ESTOQUE' AS MOV_ESTOQUE
	, 'CLIFOR_COD' AS CLIFOR_COD
	, 'CLIFOR_LOJA' AS CLIFOR_LOJA
	, 'NREDUZ' AS CLIFOR_NREDUZ
	, 'CLIFOR' AS CLIFOR_NOME

FROM SBF010 SBF
LEFT JOIN SB1010 SB1 ON
SB1.D_E_L_E_T_	<> '*' AND B1_COD = BF_PRODUTO
LEFT JOIN CTD010 CTD ON
CTD.D_E_L_E_T_ <> '*' AND CTD_ITEM = B1_ITEMCC
WHERE SBF.D_E_L_E_T_ <> '*'

UNION ALL

SELECT 'SD3' AS TABELA, D3_FILIAL,D3_LOCAL,D3_NUMSERI, B1_COD, B1_DESC, CTD_DESC01,
CASE
	WHEN SUBSTRING(D3_EMISSAO,7,2) + '/' + SUBSTRING(D3_EMISSAO,5,2) + '/' + SUBSTRING(D3_EMISSAO,1,4) = '  /  /    ' THEN ''
	ELSE SUBSTRING(D3_EMISSAO,7,2) + '/' + SUBSTRING(D3_EMISSAO,5,2) + '/' + SUBSTRING(D3_EMISSAO,1,4) END DT,
TRIM(D3_LOTECTL), D3_DOC, '001' AS SERIE, D3_TM,SF4.F4_TEXTO,
CASE
	WHEN D3_TM < '500' THEN 'E'
	WHEN D3_TM >= '500' THEN 'S' END CF,
CASE
	WHEN D3_TM < '500' THEN 'E'
	WHEN D3_TM >= '500' THEN 'S' END TIPO,
CASE WHEN D3_TM < '500' THEN D3_QUANT ELSE D3_QUANT * -1 END D3_QUANT, D3_IDENT, 'PEDIDO' AS PEDIDO, ISNULL(SD1.D1_TIPO, SD2.D2_TIPO) AS TIPO, ISNULL(SD1.F4_ESTOQUE, SD2.F4_ESTOQUE) AS ESTOQUE
, ISNULL(SD1.CLIFOR_COD, SD2.CLIFOR_COD) CLIFOR_COD
, ISNULL(SD1.CLIFOR_LOJA, SD2.CLIFOR_LOJA) CLIFOR_LOJA
, ISNULL(SD2.CLIFOR_NREDUZ + '  ', SD1.CLIFOR_NREDUZ) CLIFOR_NREDUZ
, ISNULL(SD1.CLIFOR_NOME, SD2.CLIFOR_NOME) CLIFOR_NOME
FROM SD3010 SD3
LEFT JOIN SB1010 SB1 ON
B1_COD = D3_COD AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN SF4010 SF4 ON
SF4.F4_CODIGO = SD3.D3_CODLAN AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN #SD1_NFS SD1 ON
D3_FILIAL = D1_FILIAL AND D3_DOC = D1_DOC AND D3_TM < '500'
LEFT JOIN #SD2_NFS SD2 ON
D3_FILIAL = D2_FILIAL AND D3_DOC = D2_DOC AND D3_TM >= '500'
WHERE SD3.D_E_L_E_T_ <> '*' 
--AND D3_EMISSAO >= '20211206'

UNION ALL

SELECT 'SDB' AS TABELA
, DB_FILIAL
, DB_LOCAL
, DB_NUMSERI AS SERIAL
, B1_COD
, B1_DESC
, CTD_DESC01,
SUBSTRING(DB_DATA,7,2) + '/' + SUBSTRING(DB_DATA,5,2) + '/' + SUBSTRING(DB_DATA,1,4) DT,
TRIM(DB_LOTECTL), DB_DOC, DB_SERIE, DB_TM

,	CASE		
		WHEN DB_TM = '499' AND DB_ORIGEM = 'SD3' THEN 'MOVIMENTO ENTRADA'
		WHEN DB_TM = '999' AND DB_ORIGEM = 'SD3' THEN 'MOVIMENTO SAIDA'
		WHEN DB_ORIGEM = 'SD1' THEN SD1_IDENT.F4_TEXTO
		WHEN DB_ORIGEM = 'SC6' THEN SD2_IDENT.F4_TEXTO
		--WHEN DB_ORIGEM = 'SD3' THEN F5_TEXTO		
		--ELSE SF4.F4_TEXTO		
		END ACT,
CASE
	WHEN DB_TM = '499' AND DB_ORIGEM = 'SD3' THEN DB_TM
	WHEN DB_TM = '999' AND DB_ORIGEM = 'SD3' THEN DB_TM
	WHEN DB_ORIGEM = 'SD1' THEN SD1_IDENT.D1_CF
	WHEN DB_ORIGEM = 'SC6' THEN SD2_IDENT.D2_CF
--	ELSE SF4.F4_TEXTO		
	END F4_CF,
CASE
	WHEN 
	--F4_TIPO IS NULL AND 
	DB_TM < '500' THEN 'E'
	WHEN
	--F4_TIPO IS NULL AND
	DB_TM >= '500' THEN 'S'
	--ELSE F4_TIPO
	END F4_TIPO,
CASE WHEN DB_TM < '500' THEN SUM(DB_QUANT) ELSE SUM(DB_QUANT) * -1 END DB_QUANT
, CASE
	WHEN DB_TM < '500' THEN D1_IDENTB6
	ELSE D2_IDENTB6 END IDENT
, CASE
	WHEN DB_TM < '500' THEN D2_PEDIDO
	ELSE D2_PEDIDO END IDENT
, ISNULL(SD1.D1_TIPO, SD2.D2_TIPO) AS TIPO
, ISNULL(SD1.F4_ESTOQUE, SD2.F4_ESTOQUE) AS ESTOQUE
, ISNULL(ISNULL(SD1.CLIFOR_COD, SD2.CLIFOR_COD),DB_CLIFOR)
, ISNULL(ISNULL(SD1.CLIFOR_LOJA, SD2.CLIFOR_LOJA), DB_LOJA)
, ISNULL(SD2.CLIFOR_NREDUZ + '  ', SD1.CLIFOR_NREDUZ)
, ISNULL(SD1.CLIFOR_NOME, SD2.CLIFOR_NOME)
FROM SDB010 SDB
LEFT JOIN SB1010 SB1 ON
B1_COD = DB_PRODUTO AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
/*LEFT JOIN SF4010 SF4 ON
SF4.F4_CODIGO = SDB.DB_TM AND SF4.D_E_L_E_T_ <> '*'*/
LEFT JOIN #SD1_NFS SD1 ON
DB_FILIAL = SD1.D1_FILIAL AND DB_DOC = D1_DOC AND DB_TM < '500' AND DB_SERIE = D1_SERIE AND DB_CLIFOR = SD1.CLIFOR_COD AND DB_LOJA = SD1.CLIFOR_LOJA
LEFT JOIN #SD2_NFS SD2 ON
DB_FILIAL = SD2.D2_FILIAL AND DB_DOC = D2_DOC AND DB_TM >= '500' AND DB_SERIE = D2_SERIE AND DB_CLIFOR = SD2.CLIFOR_COD AND DB_LOJA = SD2.CLIFOR_LOJA
LEFT JOIN (SELECT D2_CF, (SELECT F4_TEXTO FROM SF4010 SF4 WHERE F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*') F4_TEXTO,
(SELECT F4_TIPO FROM SF4010 SF4 WHERE F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*') F4_TIPO,D2_TES,D2_PEDIDO,D2_FILIAL,D2_DOC,D2_COD,D2_IDENTB6, D2_NUMSEQ, D2_SERIE FROM SD2010 WHERE D_E_L_E_T_ <> '*') SD2_IDENT ON
DB_NUMSEQ = D2_NUMSEQ AND DB_DOC = SD2_IDENT.D2_DOC AND DB_SERIE = SD2_IDENT.D2_SERIE AND DB_PRODUTO = SD2_IDENT.D2_COD AND DB_TM >= '500' AND SD2_IDENT.D2_FILIAL = DB_FILIAL
LEFT JOIN (SELECT D1_CF, (SELECT F4_TEXTO FROM SF4010 SF4 WHERE F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*') F4_TEXTO,
(SELECT F4_TEXTO FROM SF4010 SF4 WHERE F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*') F4_TIPO,D1_TES,D1_PEDIDO,D1_FILIAL,D1_DOC,D1_COD,D1_IDENTB6, D1_NUMSEQ, D1_SERIE FROM SD1010 WHERE D_E_L_E_T_ <> '*') SD1_IDENT ON
DB_NUMSEQ = D1_NUMSEQ AND DB_DOC = SD1_IDENT.D1_DOC AND DB_SERIE = SD1_IDENT.D1_SERIE AND DB_PRODUTO = SD1_IDENT.D1_COD AND DB_TM < '500' AND SD1_IDENT.D1_FILIAL = DB_FILIAL

WHERE SDB.D_E_L_E_T_ <> '*'  AND B1_TIPO = 'PA' AND DB_ESTORNO <> 'S'
GROUP BY DB_FILIAL, DB_LOCAL, B1_COD, B1_DESC, CTD_DESC01, DB_LOTECTL,DB_TM,DB_DATA, DB_DOC, SD1_IDENT.F4_TIPO, DB_SERIE, SD1.D1_TIPO, SD2.D2_TIPO, SD1.F4_ESTOQUE, SD2.F4_ESTOQUE
, SD1.CLIFOR_COD, SD2.CLIFOR_COD, SD1.CLIFOR_LOJA, SD2.CLIFOR_LOJA, SD1.CLIFOR_NOME, SD2.CLIFOR_NOME, SD1.CLIFOR_NREDUZ, SD2.CLIFOR_NREDUZ
, DB_CLIFOR, DB_LOJA, DB_NUMSERI,DB_ORIGEM, SD1_IDENT.F4_TEXTO, SD2_IDENT.F4_TEXTO, D1_CF, D2_CF, D1_IDENTB6, D2_IDENTB6, D1_PEDIDO, D2_PEDIDO

UNION ALL

SELECT
	  'Z08' AS TABELA
	, Z08_FILORI
	, Z08_LOCAL
	, right(Z08_ID,6) SERIAL
	, B1_COD, B1_DESC, CTD_DESC01
	, SUBSTRING(Z08_DATA,7,2) + '/' + SUBSTRING(Z08_DATA,5,2) + '/' + SUBSTRING(Z08_DATA,1,4) DT
	, TRIM(Z07_LOTE), SUBSTRING(Z08_NF,1,9) NF, SUBSTRING(Z08_NF,10,3) SERIE
	, 'TES' AS TES
	, Z08_ACT
	, 'CF' AS CF
	, CASE
		WHEN Z08_TIPO IN ('D', 'J', 'I') THEN 'E'
		WHEN Z08_TIPO IN ('M', 'S') THEN 'S'
	ELSE
		''
	END TIPO
	, CASE
		WHEN Z08_TIPO IN ('D', 'J', 'I') THEN 1
		WHEN Z08_TIPO IN ('M', 'S') THEN -1
	END QUANT
	, Z08_IDENT
	, 'PEDIDO' AS PEDIDO
	
	, D2_TIPO
	, F4_ESTOQUE
	, SD2.CLIFOR_COD
	, SD2.CLIFOR_LOJA
	, SD2.CLIFOR_NREDUZ
	, SD2.CLIFOR_NOME
FROM Z08010 
LEFT JOIN Z07010 ON
Z07_ID = Z08_ID AND Z07010.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
SB1.D_E_L_E_T_ <> '*' AND B1_COD = Z07_PROD
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN #SD2_NFS SD2 ON
Z08_FILORI = D2_FILIAL AND SUBSTRING(Z08_NF,1,9) = D2_DOC AND SUBSTRING(Z08_NF,10,3) = D2_SERIE
AND SUBSTRING(Z08_CLIFOR,1,6) = SD2.CLIFOR_COD AND SUBSTRING(Z08_CLIFOR,7,2) = SD2.CLIFOR_LOJA
WHERE Z08010.D_E_L_E_T_ <> '*' AND Z08_TIPO IN ('M', 'S')

UNION ALL

SELECT 'INV' AS TAB
	, B7_FILIAL FILIAL
	, B7_LOCAL ESTOQUE
	, B7_NUMSERI
	, B1_COD CODIGO
	, B1_DESC DESCRICAO
	, CTD_DESC01 LINHA
	, SUBSTRING(B7_DATA,7,2) + '/' + SUBSTRING(B7_DATA,5,2) + '/' + SUBSTRING(B7_DATA,1,4) DT
	, B7_LOTECTL
	, 'DOC' AS DOC
	, 'DOCSERI' AS DOCSERIE
	, 'TES' AS TES
	, 'F4_TEXTO' AS F4_TEXTO
	, 'CF' AS CF
	, 'EST' AS [TIPO]
	, (B7_QUANT)
	, 'IDENT' AS IDENT
	, 'PEDIDO' AS PEDIDO
	, 'D2_TIPO' AS TIPO_NF
	, 'F4_ESTOQUE' AS MOV_ESTOQUE
	, 'CLIFOR_COD' AS CLIFOR_COD
	, 'CLIFOR_LOJA' AS CLIFOR_LOJA
	, 'NREDUZ' AS CLIFOR_NREDUZ
	, 'CLIFOR' AS CLIFOR_NOME

FROM SB7010 SB7
LEFT JOIN SB1010 SB1 ON
SB1.D_E_L_E_T_	<> '*' AND B1_COD = B7_COD
LEFT JOIN CTD010 CTD ON
CTD.D_E_L_E_T_ <> '*' AND CTD_ITEM = B1_ITEMCC
WHERE SB7.D_E_L_E_T_ <> '*'
-- AND B7_DATA = '20211203'


UNION ALL

select 'SB6R' AS TABELA
,B6_FILIAL
,B6_LOCAL
, D2_NUMSERI
, B1_COD
, B1_DESC
, CTD_DESC01
, B6_EMISSAO
, D2_LOTECTL
, B6_DOC
, B6_SERIE
, B6_TES
, F4_TEXTO
, D2_CF
, 'S' AS TIPO
, SUM(B6_QUANT) * -1 QUANT
, B6_IDENT
, D2_PEDIDO
, B6_TIPO
, F4_ESTOQUE
, A1_COD CLIFOR_COD
, A1_LOJA CLIFOR_LOJA
, A1_NREDUZ CLIFOR_NREDUZ
, A1_NOME CLIFOR_NOME
FROM SB6010 SB6
LEFT JOIN SD2010 SD2 ON
( D2_FILIAL = B6_FILIAL AND D2_IDENTB6 = B6_IDENT AND B6_LOCAL = D2_LOCAL AND SD2.D_E_L_E_T_ <> '*' AND D2_DOC = B6_DOC )  	
LEFT JOIN SB1010 SB1 ON
B1_COD = B6_PRODUTO AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN SF4010 SF4 ON
F4_CODIGO = B6_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA1010 SA1 ON
A1_COD = B6_CLIFOR AND A1_LOJA = B6_LOJA AND SA1.D_E_L_E_T_ <> '*'
WHERE SB6.D_E_L_E_T_ <> '*' AND B6_PODER3 = 'R'
group by B6_FILIAL
,B6_LOCAL
, D2_NUMSERI
, B1_COD
, B1_DESC
, CTD_DESC01
, B6_EMISSAO
, D2_LOTECTL
, B6_DOC
, B6_SERIE
, B6_TES
, F4_TEXTO
, D2_CF
, B6_IDENT
, D2_PEDIDO
, B6_TIPO
, F4_ESTOQUE
, A1_COD
, A1_LOJA 
, A1_NREDUZ 
, A1_NOME 

UNION ALL


select 'SB6D' AS TABELA
,B6_FILIAL
,B6_LOCAL
, D1_XSERIAL
, B1_COD
, B1_DESC
, CTD_DESC01
, B6_EMISSAO
, D1_LOTECTL
, B6_DOC
, B6_SERIE
, B6_TES
, F4_TEXTO
, D1_CF
, 'E' AS TIPO
, SUM(B6_QUANT) QUANT
, B6_IDENT
, D1_PEDIDO
, B6_TIPO
, F4_ESTOQUE
, A1_COD CLIFOR_COD
, A1_LOJA CLIFOR_LOJA
, A1_NREDUZ CLIFOR_NREDUZ
, A1_NOME CLIFOR_NOME
FROM SB6010 SB6
LEFT JOIN SD1010 SD1 ON
( D1_FILIAL = B6_FILIAL AND D1_IDENTB6 = B6_IDENT AND B6_LOCAL = D1_LOCAL AND SD1.D_E_L_E_T_ <> '*' AND D1_DOC = B6_DOC )  	
LEFT JOIN SB1010 SB1 ON
B1_COD = B6_PRODUTO AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN SF4010 SF4 ON
F4_CODIGO = B6_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA1010 SA2 ON
A1_COD = B6_CLIFOR AND A1_LOJA = B6_LOJA AND SA2.D_E_L_E_T_ <> '*'
WHERE SB6.D_E_L_E_T_ <> '*' AND B6_PODER3 = 'D'
group by B6_FILIAL
,B6_LOCAL
, D1_XSERIAL
, B1_COD
, B1_DESC
, CTD_DESC01
, B6_EMISSAO
, D1_LOTECTL
, B6_DOC
, B6_SERIE
, B6_TES
, F4_TEXTO
, D1_CF
, B6_IDENT
, D1_PEDIDO
, B6_TIPO
, F4_ESTOQUE
, A1_COD
, A1_LOJA 
, A1_NREDUZ 
, A1_NOME 
) t
