USE PUOBH2

SELECT
	  B6_FILIAL  FILIAL
	, A1_COD  CLIENTE
	, A1_NOME NOME
	, A1_LOJA LOJA
	, A1_NREDUZ NREDUZ
	, A1_EST ESTADO
	, B6_DOC  [N.FISCAL]
	, B6_EMISSAO EMISSAO
	, A3_COD [CÓD. VENDEDOR]
	, A3_NOME VENDEDOR
	, A3_NREDUZ [NREDUZ VENDEDOR]
	, B1_GRUPO  GRUPO 
	, CTH_DESC01 [DESCRICAO GRUPO]
	, CTT_CUSTO  DEPARTAMENTO
	, CTT_DESC01 [DESC. DEPTO]
	, CTD_ITEM  LINHA
	, CTD_DESC01 [DESCRICAO LINHA]
	, B1_COD PRODUTO
	, B1_DESC  DESCRICAO
	, D2_LOTECTL LOTE
	, D2_NUMSERI SERIAL
	, B6_IDENT IDENT
	, B8_DTVALID VALIDADE
	, B6_SALDO [SALDO NF]
	, B6_PRUNIT [VLR UNIT]
	, B6_SALDO * B6_PRUNIT [VLR TOTAL]
	, ISNULL( (SELECT C6_QTDVEN FROM SC6010 WHERE C6_NUMSERI <> '' AND C6_NOTA = '' AND  D_E_L_E_T_ <> '*' AND C6_NUMSERI = D2_NUMSERI AND LEFT(C6_NUM, 1) = 'R' ),0) RESERVA
	, (B6_SALDO - ISNULL( (SELECT C6_QTDVEN FROM SC6010 WHERE C6_NUMSERI <> ''  AND C6_NOTA = '' AND D_E_L_E_T_ <> '*' AND C6_NUMSERI = D2_NUMSERI AND LEFT(C6_NUM, 1) = 'R' ),0))  [SLD DISP.]
	, B6_TES TES	
	FROM SB6010 SB6
LEFT JOIN SA1010 SA1 ON 
A1_COD = B6_CLIFOR AND A1_LOJA = B6_LOJA AND SA1.D_E_L_E_T_ <> '*'
LEFT JOIN SF2010 SF2 ON
F2_DOC = B6_DOC AND F2_SERIE = B6_SERIE AND F2_FILIAL = B6_FILIAL AND SF2.D_E_L_E_T_ <> '*' AND F2_CLIENTE = B6_CLIFOR AND F2_LOJA = B6_LOJA
LEFT JOIN SA3010 SA3 ON
F2_VEND1 = A3_COD AND SA3.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
B1_COD = B6_PRODUTO AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTH010 CTH ON
CTH_CLVL = B1_CLVL AND CTH.D_E_L_E_T_ <> '*'
LEFT JOIN CTT010 CTT ON
( B1_CC   = CTT_CUSTO AND CTT.D_E_L_E_T_ <> '*' )
LEFT JOIN CTD010 CTD ON
( B1_ITEMCC = CTD_ITEM AND CTD.D_E_L_E_T_ <> '*' )  
LEFT JOIN SD2010 SD2 ON
( D2_FILIAL = B6_FILIAL AND D2_IDENTB6 = B6_IDENT AND B6_LOCAL = D2_LOCAL AND SD2.D_E_L_E_T_ <> '*' )  	
LEFT JOIN (SELECT DISTINCT B8_PRODUTO, B8_LOTECTL, B8_DTVALID, B8_FILIAL, B8_LOCAL FROM SB8010 WHERE D_E_L_E_T_ <> '*' ) SB8 ON
B1_COD = B8_PRODUTO AND D2_LOTECTL = B8_LOTECTL AND B6_FILIAL = B8_FILIAL AND B8_LOCAL = B6_LOCAL
WHERE SB6.D_E_L_E_T_ <> '*'
--AND B6_EMISSAO >= '20191101'
AND B6_PODER3 = 'R'
