USE PUOBH2

IF OBJECT_ID('tempdb..#SD2_NFS') IS NOT NULL DROP TABLE #SD2_NFS

SELECT * INTO #SD2_NFS FROM (
SELECT DISTINCT D2_DOC, D2_FILIAL, D2_SERIE, D2_TIPO, F4_ESTOQUE
, ISNULL(A2_COD,A1_COD) CLIFOR_COD, ISNULL(A2_LOJA,A1_LOJA) CLIFOR_LOJA, ISNULL(A2_NREDUZ + '  ',A1_NREDUZ) CLIFOR_NREDUZ, ISNULL(A2_NOME,A1_NOME) CLIFOR_NOME
FROM SD2010 SD2
LEFT JOIN SF4010 SF4 ON F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA1010 SA1 ON A1_COD = D2_CLIENTE AND A1_LOJA = D2_LOJA AND SA1.D_E_L_E_T_ <> '*' AND NOT D2_TIPO IN ('B','D')
LEFT JOIN SA2010 SA2 ON A2_COD = D2_CLIENTE AND A2_LOJA = D2_LOJA AND SA2.D_E_L_E_T_ <> '*' AND D2_TIPO IN ('B','D')
WHERE SD2.D_E_L_E_T_ <> '*') t

IF OBJECT_ID('tempdb..#SD1_NFS') IS NOT NULL DROP TABLE #SD1_NFS
SELECT * INTO #SD1_NFS FROM (
SELECT TOP 1 WITH TIES D1_DOC, D1_FILIAL, D1_SERIE, D1_TIPO, F4_ESTOQUE
, ISNULL(A2_COD,A1_COD) CLIFOR_COD, ISNULL(A2_LOJA,A1_LOJA) CLIFOR_LOJA, ISNULL(A2_NREDUZ + '  ', A1_NREDUZ) CLIFOR_NREDUZ, ISNULL(A2_NOME,A1_NOME) CLIFOR_NOME
FROM SD1010 SD1
LEFT JOIN SF4010 SF4 ON F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA2010 SA2 ON A2_COD = D1_FORNECE AND A2_LOJA = D1_LOJA AND SA2.D_E_L_E_T_ <> '*' AND NOT D1_TIPO IN ('B','D')
LEFT JOIN SA1010 SA1 ON A1_COD = D1_FORNECE AND A1_LOJA = D1_LOJA AND SA1.D_E_L_E_T_ <> '*' AND D1_TIPO IN ('B','D')
WHERE SD1.D_E_L_E_T_ <> '*'
ORDER BY ROW_NUMBER() OVER(PARTITION BY D1_DOC, D1_FILIAL, A2_COD, A1_COD, A2_LOJA, A1_LOJA ORDER BY D1_DOC, D1_FILIAL, D1_SERIE, D1_TIPO, A2_LOJA, A1_LOJA )) u

IF OBJECT_ID('tempdb..#ult_preco') IS NOT NULL DROP TABLE #ult_preco

SELECT * INTO #ult_preco FROM(
SELECT TOP 1 WITH TIES CTD_DESC01 LINHA,D2_EMISSAO,B1_COD PRODUTO, D2_PRCVEN, D2_CUSTO1/NULLIF(D2_QUANT,0) CUSTO_UNIT FROM SD2010 SD2
LEFT JOIN SF4010 SF4 ON
F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
B1_COD = D2_COD AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
WHERE SD2.D_E_L_E_T_ <> '*' AND F4_DUPLIC = 'S' AND D2_TIPO IN ('C','P','N','I')
AND D2_EMISSAO <= (SELECT TOP 1 B9_DATA FROM SB9010 WHERE D_E_L_E_T_ <> '*' AND B9_FILIAL = D2_FILIAL ORDER BY 1 DESC)
--AND B1_COD LIKE '%5MAX%'
ORDER BY ROW_NUMBER() OVER (PARTITION BY D2_COD ORDER BY D2_COD, D2_EMISSAO DESC)
)t

IF OBJECT_ID('tempdb..#ult_custo') IS NOT NULL DROP TABLE #ult_custo

SELECT * INTO #ult_custo FROM(

SELECT TOP 1 WITH TIES B1_COD PRODUTO, D1_DTDIGIT,D1_CUSTO / NULLIF(D1_QUANT,0) CUSTO_UNIT  FROM SD1010 SD1
LEFT JOIN SF4010 SF4 ON
F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
B1_COD = D1_COD AND SB1.D_E_L_E_T_ <> '*'
WHERE SD1.D_E_L_E_T_ <> '*' AND F4_TEXTO LIKE '%COMPRA%'
ORDER BY ROW_NUMBER() OVER (PARTITION BY B1_COD ORDER BY D1_DTDIGIT DESC)
) t

IF OBJECT_ID('tempdb..#Z08S') IS NOT NULL DROP TABLE #Z08S

SELECT * INTO #Z08S FROM (
SELECT
	  'SER' AS TABELA
	, Z08_FILORI
	, Z08_LOCAL
	, B1_COD, B1_DESC, CTD_DESC01
	, SUBSTRING(Z08_DATA,7,2) + '/' + SUBSTRING(Z08_DATA,5,2) + '/' + SUBSTRING(Z08_DATA,1,4) DT
	,  SUBSTRING(Z08_DATA,1,4) + SUBSTRING(Z08_DATA,5,2) + SUBSTRING(Z08_DATA,7,2) DT_NUM
	, TRIM(Z07_LOTE) LOTE, SUBSTRING(Z08_NF,1,9) NF, SUBSTRING(Z08_NF,10,3) SERIE
	, 'TES' AS TES
	, Z08_ACT
	, 'CF' AS CF
	, CASE
		WHEN Z08_TIPO IN ('D', 'J') THEN 'E'
		WHEN Z08_TIPO IN ('M', 'S') THEN 'S'
	ELSE
		''
	END TIPO
	, CASE
		WHEN Z08_TIPO IN ('D', 'J') THEN 1
		WHEN Z08_TIPO IN ('M', 'S') THEN -1
	END QUANT
	, Z08_IDENT
	, 'PEDIDO' AS PEDIDO
	, Z08_ID
	, D2_TIPO
	, F4_ESTOQUE
	, SD2.CLIFOR_COD
	, SD2.CLIFOR_LOJA
	, SD2.CLIFOR_NREDUZ
	, SD2.CLIFOR_NOME
	, Z08_USER
FROM Z08010 
LEFT JOIN Z07010 ON
Z07_ID = Z08_ID AND Z07010.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
SB1.D_E_L_E_T_ <> '*' AND B1_COD = Z07_PROD
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN #SD2_NFS SD2 ON
Z08_FILORI = D2_FILIAL AND SUBSTRING(Z08_NF,1,9) = D2_DOC AND SUBSTRING(Z08_NF,10,3) = D2_SERIE
AND SUBSTRING(Z08_CLIFOR,1,6) = SD2.CLIFOR_COD AND SUBSTRING(Z08_CLIFOR,7,2) = SD2.CLIFOR_LOJA
LEFT JOIN (
	SELECT B6_IDENT, B6_PRODUTO, B6_PODER3, SUM(B6_SALDO) SALDO, B6_DOC, B6_SERIE,B6_FILIAL FROM SB6010 WHERE D_E_L_E_T_ <> '*'  GROUP BY B6_IDENT, B6_PRODUTO, B6_PODER3,B6_DOC,B6_FILIAL,B6_SERIE) SB6 ON
	B6_IDENT = Z08_IDENT AND B6_PRODUTO = B1_COD AND B6_PODER3 = 'R' AND B6_FILIAL = Z08_FILORI
WHERE Z08010.D_E_L_E_T_ <> '*' AND Z08_TIPO IN ('M', 'S')
AND Z08_ACT LIKE '%REM%'
AND SALDO >0
--AND Z08_IDENT = '521333'
) t;

IF OBJECT_ID('tempdb..#Z08E') IS NOT NULL DROP TABLE #Z08E

SELECT * INTO #Z08E FROM (
SELECT * FROM (
SELECT
	  'SER' AS TABELA
	, Z08_USER
	, Z08_FILORI
	, Z08_LOCAL
	, B1_COD, B1_DESC, CTD_DESC01
	, SUBSTRING(Z08_DATA,7,2) + '/' + SUBSTRING(Z08_DATA,5,2) + '/' + SUBSTRING(Z08_DATA,1,4) DT
	, TRIM(Z07_LOTE) LOTE, SUBSTRING(Z08_NF,1,9) NF, SUBSTRING(Z08_NF,10,3) SERIE
	, F3_OBSERV
	, 'TES' AS TES
	, Z08_ACT
	, 'CF' AS CF
	, CASE
		WHEN Z08_TIPO IN ('D', 'J', 'I') THEN 'E'
		WHEN Z08_TIPO IN ('M', 'S') THEN 'S'
	ELSE
		''
	END TIPO
	, CASE
		WHEN Z08_TIPO IN ('D', 'J', 'I') THEN 1
		WHEN Z08_TIPO IN ('M', 'S') THEN -1
	END QUANT
	, Z08_IDENT
	, 'PEDIDO' AS PEDIDO
	, Z08_ID
	, D1_TIPO
	, F4_ESTOQUE
	, ISNULL(SD1.CLIFOR_COD, Z08_CLIFOR) CLIFOR_COD
	, ISNULL(SD1.CLIFOR_LOJA, '01') CLIFOR_LOJA
	, ISNULL(SD1.CLIFOR_NREDUZ, Z08_NOMECF) CLIFOR_NREDUZ
	, ISNULL(SD1.CLIFOR_NOME, Z08_NOMECF) CLIFOR_NOME
	, ISNULL(B6_DOC, SUBSTRING(F3_OBSERV, 12, 9)) NF_ORIG
	, ISNULL(B6_SERIE, SUBSTRING(F3_OBSERV, 22, 3)) SERIE_ORIG
FROM Z08010 
LEFT JOIN Z07010 ON
Z07_ID = Z08_ID AND Z07010.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
SB1.D_E_L_E_T_ <> '*' AND B1_COD = Z07_PROD
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN #SD1_NFS SD1 ON
Z08_FILORI = D1_FILIAL AND SUBSTRING(Z08_NF,1,9) = D1_DOC AND SUBSTRING(Z08_NF,10,3) = D1_SERIE
AND SUBSTRING(Z08_CLIFOR,1,6) = SD1.CLIFOR_COD AND SUBSTRING(Z08_CLIFOR,7,2) = SD1.CLIFOR_LOJA
LEFT JOIN (SELECT DISTINCT F3_NFISCAL, F3_FILIAL, F3_OBSERV FROM SF3010 WHERE D_E_L_E_T_ <> '*') SFE ON
F3_NFISCAL = SUBSTRING(Z08_NF,1,9) AND F3_FILIAL = Z08_FILORI
LEFT JOIN (
	SELECT B6_IDENT, B6_PRODUTO, B6_PODER3, SUM(B6_SALDO) SALDO, B6_DOC, B6_SERIE,B6_FILIAL FROM SB6010 WHERE D_E_L_E_T_ <> '*'  GROUP BY B6_IDENT, B6_PRODUTO, B6_PODER3,B6_DOC,B6_FILIAL,B6_SERIE) SB6 ON
	B6_IDENT = Z08_IDENT AND B6_PRODUTO = B1_COD AND B6_PODER3 = 'R' AND B6_FILIAL = Z08_FILORI
WHERE Z08010.D_E_L_E_T_ <> '*' AND Z08_TIPO IN ('D', 'J')
AND (Z08_ACT LIKE '%REM%' OR Z08_ACT LIKE '%RETORNO DEM%')
) u
LEFT JOIN (SELECT DISTINCT F2_DOC, F2_SERIE, F2_FILIAL FROM SF2010 WHERE D_E_L_E_T_ <> '*') SF2 ON
F2_DOC = NF_ORIG AND F2_SERIE = SERIE_ORIG AND F2_FILIAL = Z08_FILORI
) v

/*SELECT * FROM #Z08E
LEFT JOIN (
	SELECT B6_IDENT, B6_PRODUTO, B6_PODER3, SUM(B6_SALDO) SALDO FROM SB6010 WHERE D_E_L_E_T_ <> '*'  GROUP BY B6_IDENT, B6_PRODUTO, B6_PODER3) SB6 ON
	B6_IDENT = Z08_IDENT AND B6_PRODUTO = B1_COD AND B6_PODER3 = 'R'
where Z08_ID LIKE '%010649%'
WHERE F2_DOC IS NULL*/

IF OBJECT_ID('tempdb..#Z08V') IS NOT NULL DROP TABLE #Z08V

SELECT * INTO #Z08V FROM (
SELECT
  --TOP 2 WITH TIES 
  Z08_ID
, count(Z08_ORDEM) COUNT_ORDEM
FROM Z08010 
LEFT JOIN Z07010 ON
Z07_ID = Z08_ID AND Z07010.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
SB1.D_E_L_E_T_ <> '*' AND B1_COD = Z07_PROD
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN #SD2_NFS SD2 ON
Z08_FILORI = D2_FILIAL AND SUBSTRING(Z08_NF,1,9) = D2_DOC AND SUBSTRING(Z08_NF,10,3) = D2_SERIE
AND SUBSTRING(Z08_CLIFOR,1,6) = SD2.CLIFOR_COD AND SUBSTRING(Z08_CLIFOR,7,2) = SD2.CLIFOR_LOJA
WHERE Z08010.D_E_L_E_T_ <> '*' AND Z08_TIPO IN ('M', 'S')
AND Z08_ACT LIKE '%VEND%' 
GROUP BY Z08_ID
--ORDER BY 2 DESC
--ORDER BY ROW_NUMBER() OVER (PARTITION BY Z08_ID ORDER BY Z08_ORDEM DESC)
) s

IF OBJECT_ID('tempdb..#Z08D') IS NOT NULL DROP TABLE #Z08D

SELECT * INTO #Z08D FROM (
SELECT
  --TOP 1 WITH TIES 
  Z08_ID
, COUNT(Z08_ORDEM) COUNT_ORDEM
FROM Z08010 
LEFT JOIN Z07010 ON
Z07_ID = Z08_ID AND Z07010.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
SB1.D_E_L_E_T_ <> '*' AND B1_COD = Z07_PROD
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN #SD2_NFS SD2 ON
Z08_FILORI = D2_FILIAL AND SUBSTRING(Z08_NF,1,9) = D2_DOC AND SUBSTRING(Z08_NF,10,3) = D2_SERIE
AND SUBSTRING(Z08_CLIFOR,1,6) = SD2.CLIFOR_COD AND SUBSTRING(Z08_CLIFOR,7,2) = SD2.CLIFOR_LOJA
WHERE Z08010.D_E_L_E_T_ <> '*' AND Z08_TIPO IN ('D')
AND Z08_ACT LIKE '%DEV%VEND%' 
--ORDER BY ROW_NUMBER() OVER (PARTITION BY Z08_ID ORDER BY Z08_ORDEM DESC)
GROUP BY Z08_ID
--ORDER BY 2 DESC
) d 

IF OBJECT_ID('tempdb..#Z08DV') IS NOT NULL DROP TABLE #Z08DV

SELECT * INTO #Z08DV FROM (
	SELECT #Z08V.Z08_ID,
	#Z08V.COUNT_ORDEM - ISNULL(#Z08D.COUNT_ORDEM,0) FATURADO FROM #Z08V
	LEFT JOIN #Z08D ON
	#Z08V.Z08_ID = #Z08D.Z08_ID
	--WHERE #Z08D.Z08_ID IS NULL
	where (#Z08V.COUNT_ORDEM - ISNULL(#Z08D.COUNT_ORDEM,0)) > 0
	--ORDER BY 2 DESC
	) t

--SELECT DISTINCT Z08_ID FROM Z08010 WHERE D_E_L_E_T_ <> '*' AND Z08_ACT LIKE '%VEND%' AND Z08_TIPO = 'S'

/*SELECT
  TOP 1 WITH TIES 
  Z08_ID
, Z08_ORDEM
FROM Z08010 WHERE Z08_ACT LIKE '%VEND%' AND D_E_L_E_T_ <> '*' AND Z08_TIPO = 'S'
ORDER BY ROW_NUMBER() OVER (PARTITION BY Z08_ID ORDER BY Z08_ORDEM DESC)

SELECT * FROM Z08010 WHERE Z08_ID = '00000000000000027380'*/

IF OBJECT_ID('tempdb..#Z08FINAL') IS NOT NULL DROP TABLE #Z08FINAL

SELECT * INTO #Z08FINAL FROM (
select 
	'SER' AS TABELA
	, #Z08S.Z08_USER S_USER
	, #Z08E.Z08_USER E_USER
	, #Z08S.Z08_FILORI
	, #Z08S.Z08_LOCAL
	, #Z08S.B1_COD
	, #Z08S.B1_DESC
	, #Z08S.CTD_DESC01
	, #Z08S.DT
	, #Z08S.LOTE
	, #Z08S.NF
	, #Z08S.SERIE
	, 'TES' AS TES
	, #Z08S.Z08_ACT
	, 'CF' AS CF
	, #Z08S.TIPO
	, #Z08S.QUANT S_QUANT
	, CASE
		WHEN D1_DTDIGIT >= '20211206' THEN		
			ISNULL(D1_QUANT,0)
		ELSE 
			IIF(ISNULL(#Z08DV.Z08_ID, ISNULL(#Z08E.QUANT,0)) = #Z08S.Z08_ID, 1,
			ISNULL(#Z08DV.Z08_ID, ISNULL(#Z08E.QUANT,0)))
		END E_QUANT
	, #Z08S.Z08_IDENT
	, #Z08S.Z08_ID
	, #Z08S.D2_TIPO
	, #Z08S.F4_ESTOQUE
	, #Z08S.CLIFOR_COD
	, #Z08S.CLIFOR_LOJA
	, #Z08S.CLIFOR_NREDUZ
	, #Z08S.CLIFOR_NOME
FROM #Z08S
LEFT JOIN #Z08E ON
	#Z08S.Z08_IDENT = #Z08E.Z08_IDENT
AND #Z08S.Z08_ID = #Z08E.Z08_ID
AND #Z08S.B1_COD = #Z08E.B1_COD
and #Z08S.CLIFOR_COD = #Z08E.CLIFOR_COD
AND #Z08S.NF = #Z08E.F2_DOC
AND #Z08S.SERIE = #Z08E.F2_SERIE
LEFT JOIN #Z08DV ON
#Z08DV.Z08_ID = #Z08S.Z08_ID
left join
	(select D1_XSERIAL, D1_COD, D1_LOJA, D1_FORNECE, D1_SERIE, D1_NFORI, D1_QUANT, D1_DTDIGIT from SDB010 DB 
			LEFT JOIN SD1010 SD1 ON
			D1_FILIAL = DB_FILIAL AND D1_FORNECE = DB_CLIFOR AND D1_LOJA = DB_LOJA AND SD1.D_E_L_E_T_ <> '*' AND D1_COD = DB_PRODUTO AND D1_DOC = DB_DOC AND D1_SERIE = DB_SERIE AND DB_ORIGEM = 'SD1'
			WHERE DB.D_E_L_E_T_ <> '*' AND DB_DATA >= '20211206' AND DB_ORIGEM = 'SD1' AND DB_ESTORNO <> 'S') DB_E ON
RIGHT(#Z08S.Z08_ID,6) = D1_XSERIAL
AND #Z08S.B1_COD = D1_COD
and #Z08S.CLIFOR_COD = D1_FORNECE
AND #Z08S.NF = D1_NFORI
AND #Z08S.SERIE = D1_SERIE
WHERE
	#Z08S.Z08_ID <> ''
AND #Z08S.Z08_IDENT <> ''
--AND #Z08S.Z08_IDENT = '496175'
--AND #Z08S.Z08_ID = '00000000000000038597'
--and #Z08S.NF = '000021080'
--and t.B1_COD = 'SQUID18        '
--AND #Z08S.NF = '000023252'
) f
--SELECT D1_XSERIAL, D1_SERIE, D1_FORNECE,* FROM SD1010 WHERE D1_XSERIAL LIKE '%49677%' AND D1_NFORI LIKE '%23252%'
--SELECT Z08_IDENT,NF,SERIE,CLIFOR_COD,RIGHT(#Z08S.Z08_ID,6) FROM #Z08S WHERE Z08_ID LIKE '%49677%'

SELECT 

	TABELA
	, FILIAL
	, CLIENTE
	, LOJA
	, NOME
	, NREDUZ
	, ESTADO
	, [N.FISCAL]
	, EMISSAO
	, [CÓD. VENDEDOR]
	, VENDEDOR
	, [NREDUZ VENDEDOR]
	, GRUPO 
	, [DESCRICAO GRUPO]
	, DEPARTAMENTO
	, [DESC. DEPTO]
	, t.LINHA
	, [DESCRICAO LINHA]
	, t.PRODUTO
	, DESCRICAO
	, LOTE
	, SERIAL
	, IDENT
	, VALIDADE
	, [SALDO NF]
	, [VLR UNIT]
	, [VLR TOTAL]
	, RESERVA
	, [SLD DISP.]
	, TES
	,CASE
		WHEN #ult_preco.CUSTO_UNIT = 0 THEN #ult_custo.CUSTO_UNIT
		WHEN #ult_preco.CUSTO_UNIT IS NULL THEN #ult_custo.CUSTO_UNIT
		ELSE #ult_preco.CUSTO_UNIT END CUSTO_UNIT
FROM (
SELECT
	'SB6' AS TABELA
	, B6_FILIAL  FILIAL
	, A1_COD  CLIENTE
	, A1_LOJA LOJA
	, A1_NOME NOME
	, A1_NREDUZ NREDUZ
	, A1_EST ESTADO
	, B6_DOC  [N.FISCAL]
	, SUBSTRING(B6_EMISSAO,7,2) + '/' + SUBSTRING(B6_EMISSAO,5,2) + '/' + SUBSTRING(B6_EMISSAO,1,4) EMISSAO
	, A3_COD [CÓD. VENDEDOR]
	, A3_NOME VENDEDOR
	, A3_NREDUZ [NREDUZ VENDEDOR]
	, B1_GRUPO  GRUPO 
	, CTH_DESC01 [DESCRICAO GRUPO]
	, CTT_CUSTO  DEPARTAMENTO
	, CTT_DESC01 [DESC. DEPTO]
	, CTD_ITEM  LINHA
	, CTD_DESC01 [DESCRICAO LINHA]
	, B1_COD PRODUTO
	, B1_DESC  DESCRICAO
	, TRIM(D2_LOTECTL) LOTE
	, D2_NUMSERI SERIAL
	, B6_IDENT IDENT
	, B8_DTVALID VALIDADE
	, B6_SALDO [SALDO NF]
	, B6_PRUNIT [VLR UNIT]
	, B6_SALDO * B6_PRUNIT [VLR TOTAL]
	, ISNULL( (SELECT C6_QTDVEN FROM SC6010 WHERE C6_NUMSERI <> '' AND C6_NOTA = '' AND  D_E_L_E_T_ <> '*' AND C6_NUMSERI = D2_NUMSERI AND LEFT(C6_NUM, 1) = 'R' ),0) RESERVA
	, (B6_SALDO - ISNULL( (SELECT C6_QTDVEN FROM SC6010 WHERE C6_NUMSERI <> ''  AND C6_NOTA = '' AND D_E_L_E_T_ <> '*' AND C6_NUMSERI = D2_NUMSERI AND LEFT(C6_NUM, 1) = 'R' ),0))  [SLD DISP.]
	, B6_TES TES	
	FROM SB6010 SB6
LEFT JOIN SA1010 SA1 ON 
A1_COD = B6_CLIFOR AND A1_LOJA = B6_LOJA AND SA1.D_E_L_E_T_ <> '*'
LEFT JOIN SF2010 SF2 ON
F2_DOC = B6_DOC AND F2_SERIE = B6_SERIE AND F2_FILIAL = B6_FILIAL AND SF2.D_E_L_E_T_ <> '*' AND F2_CLIENTE = B6_CLIFOR AND F2_LOJA = B6_LOJA
LEFT JOIN SA3010 SA3 ON
F2_VEND1 = A3_COD AND SA3.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
B1_COD = B6_PRODUTO AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTH010 CTH ON
CTH_CLVL = B1_CLVL AND CTH.D_E_L_E_T_ <> '*'
LEFT JOIN CTT010 CTT ON
( B1_CC   = CTT_CUSTO AND CTT.D_E_L_E_T_ <> '*' )
LEFT JOIN CTD010 CTD ON
( B1_ITEMCC = CTD_ITEM AND CTD.D_E_L_E_T_ <> '*' )  
LEFT JOIN SD2010 SD2 ON
( D2_FILIAL = B6_FILIAL AND D2_IDENTB6 = B6_IDENT AND B6_LOCAL = D2_LOCAL AND SD2.D_E_L_E_T_ <> '*' )  	
LEFT JOIN (SELECT DISTINCT B8_PRODUTO, B8_LOTECTL, B8_DTVALID, B8_FILIAL, B8_LOCAL FROM SB8010 WHERE D_E_L_E_T_ <> '*' ) SB8 ON
B1_COD = B8_PRODUTO AND D2_LOTECTL = B8_LOTECTL AND B6_FILIAL = B8_FILIAL AND B8_LOCAL = B6_LOCAL
WHERE SB6.D_E_L_E_T_ <> '*'
AND B6_EMISSAO < '20190829'
AND B6_PODER3 = 'R'
and B6_SALDO > 0

UNION

SELECT
	'Z08' AS TABELA
	, Z08_FILORI FILIAL
	, CLIFOR_COD CLIENTE
	, CLIFOR_LOJA LOJA
	, CLIFOR_NOME NOME
	, CLIFOR_NREDUZ NREDUZ
	, 'EST' ESTADO
	, NF [N.FISCAL]
	, DT EMISSAO
	, A3_COD [CÓD. VENDEDOR]
	, A3_NOME VENDEDOR
	, A3_NREDUZ [NREDUZ VENDEDOR]
	, B1_CLVL  GRUPO 
	, 'CTH_DESC01' [DESCRICAO GRUPO]
	, B1_CC  DEPARTAMENTO
	, 'CTT_DESC01' [DESC. DEPTO]
	, B1_ITEMCC  LINHA
	, 'CTD_DESC01' [DESCRICAO LINHA]
	, #Z08FINAL.B1_COD PRODUTO
	, B1_DESC  DESCRICAO
	, LOTE LOTE
	, SUBSTRING(Z08_ID,15,6) SERIAL
	, Z08_IDENT IDENT
	, B8_DTVALID VALIDADE
	, -S_QUANT -E_QUANT [SALDO NF]
	, PRECO [VLR UNIT]
	, PRECO * (-S_QUANT -E_QUANT) [VLR TOTAL]
	, ISNULL( (SELECT sum(C6_QTDVEN) FROM SC6010 WHERE C6_NUMSERI <> '' AND C6_NOTA = '' AND  D_E_L_E_T_ <> '*' AND C6_NUMSERI = SUBSTRING(Z08_ID,15, 6) AND LEFT(C6_NUM, 1) = 'R' 
							
	),0) RESERVA
	,  (-S_QUANT -E_QUANT) - ISNULL( (SELECT sum(C6_QTDVEN) FROM SC6010 WHERE C6_NUMSERI <> '' AND C6_NOTA = '' AND  D_E_L_E_T_ <> '*' AND C6_NUMSERI = SUBSTRING(Z08_ID,15, 6) AND LEFT(C6_NUM, 1) = 'R' ),0) [SLD DISP.]
	, D2_TES TES	
FROM #Z08FINAL
LEFT JOIN (SELECT DISTINCT SUM(D2_TOTAL)/ SUM(D2_QUANT) PRECO, D2_FILIAL, D2_DOC, D2_SERIE, D2_COD, D2_VEND1, D2_TES FROM SD2010 WHERE D_E_L_E_T_ <> '*' GROUP BY D2_FILIAL, D2_DOC, D2_SERIE, D2_COD, D2_VEND1, D2_TES) SD2 ON
D2_FILIAL = Z08_FILORI AND D2_DOC = NF AND D2_SERIE = SERIE AND D2_COD = B1_COD
LEFT JOIN SF2010 SF2 ON
F2_DOC = D2_DOC AND F2_SERIE = D2_SERIE AND F2_FILIAL = D2_FILIAL AND SF2.D_E_L_E_T_ <> '*' --AND F2_CLIENTE = B6_CLIFOR AND F2_LOJA = B6_LOJA
LEFT JOIN SA3010 SA3 ON
F2_VEND1 = A3_COD AND SA3.D_E_L_E_T_ <> '*'
LEFT JOIN (SELECT B1_COD, B1_ITEMCC, B1_CLVL, B1_CC FROM SB1010 WHERE D_E_L_E_T_ <> '*') SB1 ON
SB1.B1_COD = #Z08FINAL.B1_COD
left join (select DISTINCT B8_FILIAL, B8_PRODUTO,B8_LOTECTL, B8_DTVALID, B8_LOCAL FROM SB8010 WHERE D_E_L_E_T_ <> '*') SB8 ON
B8_LOTECTL = LOTE AND SB1.B1_COD = B8_PRODUTO AND B8_FILIAL = Z08_FILORI AND B8_LOCAL = Z08_LOCAL
WHERE (-S_QUANT -E_QUANT) > 0

UNION ALL

SELECT
	'Z08' AS TABELA
	, B6_FILIAL  FILIAL
	, A1_COD  CLIENTE
	, A1_LOJA LOJA
	, A1_NOME NOME
	, A1_NREDUZ NREDUZ
	, A1_EST ESTADO
	, B6_DOC  [N.FISCAL]
	, SUBSTRING(B6_EMISSAO,7,2) + '/' + SUBSTRING(B6_EMISSAO,5,2) + '/' + SUBSTRING(B6_EMISSAO,1,4) EMISSAO
	, A3_COD [CÓD. VENDEDOR]
	, A3_NOME VENDEDOR
	, A3_NREDUZ [NREDUZ VENDEDOR]
	, B1_GRUPO  GRUPO 
	, CTH_DESC01 [DESCRICAO GRUPO]
	, CTT_CUSTO  DEPARTAMENTO
	, CTT_DESC01 [DESC. DEPTO]
	, CTD_ITEM  LINHA
	, CTD_DESC01 [DESCRICAO LINHA]
	, B1_COD PRODUTO
	, B1_DESC  DESCRICAO
	, TRIM(D2_LOTECTL) LOTE
	, D2_NUMSERI SERIAL
	, B6_IDENT IDENT
	, B8_DTVALID VALIDADE
	, B6_SALDO [SALDO NF]
	, B6_PRUNIT [VLR UNIT]
	, B6_SALDO * B6_PRUNIT [VLR TOTAL]
	, ISNULL( (SELECT C6_QTDVEN FROM SC6010 WHERE C6_NUMSERI <> '' AND C6_NOTA = '' AND  D_E_L_E_T_ <> '*' AND C6_NUMSERI = D2_NUMSERI AND LEFT(C6_NUM, 1) = 'R' ),0) RESERVA
	, (B6_SALDO - ISNULL( (SELECT C6_QTDVEN FROM SC6010 WHERE C6_NUMSERI <> ''  AND C6_NOTA = '' AND D_E_L_E_T_ <> '*' AND C6_NUMSERI = D2_NUMSERI AND LEFT(C6_NUM, 1) = 'R' ),0))  [SLD DISP.]
	, B6_TES TES	
	FROM SB6010 SB6
LEFT JOIN SA1010 SA1 ON 
A1_COD = B6_CLIFOR AND A1_LOJA = B6_LOJA AND SA1.D_E_L_E_T_ <> '*'
LEFT JOIN SF2010 SF2 ON
F2_DOC = B6_DOC AND F2_SERIE = B6_SERIE AND F2_FILIAL = B6_FILIAL AND SF2.D_E_L_E_T_ <> '*' AND F2_CLIENTE = B6_CLIFOR AND F2_LOJA = B6_LOJA
LEFT JOIN SA3010 SA3 ON
F2_VEND1 = A3_COD AND SA3.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
B1_COD = B6_PRODUTO AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTH010 CTH ON
CTH_CLVL = B1_CLVL AND CTH.D_E_L_E_T_ <> '*'
LEFT JOIN CTT010 CTT ON
( B1_CC   = CTT_CUSTO AND CTT.D_E_L_E_T_ <> '*' )
LEFT JOIN CTD010 CTD ON
( B1_ITEMCC = CTD_ITEM AND CTD.D_E_L_E_T_ <> '*' )  
LEFT JOIN SD2010 SD2 ON
( D2_FILIAL = B6_FILIAL AND D2_IDENTB6 = B6_IDENT AND B6_LOCAL = D2_LOCAL AND SD2.D_E_L_E_T_ <> '*' )  	
LEFT JOIN (SELECT DISTINCT B8_PRODUTO, B8_LOTECTL, B8_DTVALID, B8_FILIAL, B8_LOCAL FROM SB8010 WHERE D_E_L_E_T_ <> '*' ) SB8 ON
B1_COD = B8_PRODUTO AND D2_LOTECTL = B8_LOTECTL AND B6_FILIAL = B8_FILIAL AND B8_LOCAL = B6_LOCAL
WHERE SB6.D_E_L_E_T_ <> '*' AND B6_EMISSAO >= '20211206' AND B6_PODER3 = 'R'
and B6_SALDO > 0
) t
LEFT JOIN #ult_preco ON
t.PRODUTO = #ult_preco.PRODUTO
LEFT JOIN #ult_custo ON
t.PRODUTO = #ult_custo.PRODUTO
