USE PUOBH2;

IF OBJECT_ID('tempdb..#SD2_NFS') IS NOT NULL DROP TABLE #SD2_NFS

SELECT * INTO #SD2_NFS FROM (
SELECT DISTINCT D2_DOC, D2_FILIAL, D2_SERIE, D2_TIPO, F4_ESTOQUE
, ISNULL(A2_COD,A1_COD) CLIFOR_COD, ISNULL(A2_LOJA,A1_LOJA) CLIFOR_LOJA, ISNULL(A2_NREDUZ + '  ',A1_NREDUZ) CLIFOR_NREDUZ, ISNULL(A2_NOME,A1_NOME) CLIFOR_NOME
FROM SD2010 SD2
LEFT JOIN SF4010 SF4 ON F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA1010 SA1 ON A1_COD = D2_CLIENTE AND A1_LOJA = D2_LOJA AND SA1.D_E_L_E_T_ <> '*' AND NOT D2_TIPO IN ('B','D')
LEFT JOIN SA2010 SA2 ON A2_COD = D2_CLIENTE AND A2_LOJA = D2_LOJA AND SA2.D_E_L_E_T_ <> '*' AND D2_TIPO IN ('B','D')
WHERE SD2.D_E_L_E_T_ <> '*') t

IF OBJECT_ID('tempdb..#SD1_NFS') IS NOT NULL DROP TABLE #SD1_NFS
SELECT * INTO #SD1_NFS FROM (
SELECT TOP 1 WITH TIES D1_DOC, D1_FILIAL, D1_SERIE, D1_TIPO, F4_ESTOQUE
, ISNULL(A2_COD,A1_COD) CLIFOR_COD, ISNULL(A2_LOJA,A1_LOJA) CLIFOR_LOJA, ISNULL(A2_NREDUZ + '  ', A1_NREDUZ) CLIFOR_NREDUZ, ISNULL(A2_NOME,A1_NOME) CLIFOR_NOME
FROM SD1010 SD1
LEFT JOIN SF4010 SF4 ON F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SA2010 SA2 ON A2_COD = D1_FORNECE AND A2_LOJA = D1_LOJA AND SA2.D_E_L_E_T_ <> '*' AND NOT D1_TIPO IN ('B','D')
LEFT JOIN SA1010 SA1 ON A1_COD = D1_FORNECE AND A1_LOJA = D1_LOJA AND SA1.D_E_L_E_T_ <> '*' AND D1_TIPO IN ('B','D')
WHERE SD1.D_E_L_E_T_ <> '*'
ORDER BY ROW_NUMBER() OVER(PARTITION BY D1_DOC, D1_FILIAL, A2_COD, A1_COD, A2_LOJA, A1_LOJA ORDER BY D1_DOC, D1_FILIAL, D1_SERIE, D1_TIPO, A2_LOJA, A1_LOJA )) u

SELECT
	'SDB' AS TABELA
,	DB_DATA
,	DB_FILIAL
,	DB_DOC
,	CASE
		WHEN 
		--F4_TIPO IS NULL AND 
		DB_TM < '500' THEN 'E'
		WHEN
		--F4_TIPO IS NULL AND
		DB_TM >= '500' THEN 'S'
		--ELSE F4_TIPO
		END F4_TIPO
,	CASE		
		WHEN DB_TM = '499' AND DB_ORIGEM = 'SD3' THEN 'MOVIMENTO ENTRADA'
		WHEN DB_TM = '999' AND DB_ORIGEM = 'SD3' THEN 'MOVIMENTO SAIDA'
		WHEN DB_ORIGEM = 'SD1' THEN SD1_IDENT.F4_TEXTO
		WHEN DB_ORIGEM = 'SC6' THEN SD2_IDENT.F4_TEXTO
		--WHEN DB_ORIGEM = 'SD3' THEN F5_TEXTO		
		--ELSE SF4.F4_TEXTO		
		END ACT
, B1_COD
, B1_DESC
, ISNULL(ISNULL(SD1.CLIFOR_COD, SD2.CLIFOR_COD), DB_CLIFOR) CLIFOR_COD
, ISNULL(SD1.CLIFOR_NOME, SD2.CLIFOR_NOME) CLIFOR_NOME
, ISNULL(SD1.CLIFOR_NREDUZ, SD2.CLIFOR_NREDUZ) CLIFOR_NREDUZ
, DB_LOTECTL
, DB_NUMSERI
, CASE WHEN DB_TM < '500' THEN SUM(DB_QUANT) ELSE SUM(DB_QUANT) * -1 END DB_QUANT
, SDB.R_E_C_N_O_
, DB_IDOPERA
, isnull((SELECT USR_CODIGO FROM SYS_USR WHERE D_E_L_E_T_ <> '*' AND 
		 (substring(DB_USERLGA, 11, 1) + substring(DB_USERLGA, 15, 1) +
         substring(DB_USERLGA, 2, 1) + substring(DB_USERLGA, 6, 1) +
         substring(DB_USERLGA, 10, 1) + substring(DB_USERLGA, 14, 1) +
         substring(DB_USERLGA, 1, 1) + substring(DB_USERLGA, 5, 1) +
         substring(DB_USERLGA, 9, 1) + substring(DB_USERLGA, 13, 1) +
         substring(DB_USERLGA, 17, 1) + substring(DB_USERLGA, 4, 1) +
         substring(DB_USERLGA, 8, 1)) = USR_ID),

		 (SELECT USR_CODIGO FROM SYS_USR WHERE D_E_L_E_T_ <> '*' AND 
		 (substring(DB_USERLGI, 11, 1) + substring(DB_USERLGI, 15, 1) +
         substring(DB_USERLGI, 2, 1) + substring(DB_USERLGI, 6, 1) +
         substring(DB_USERLGI, 10, 1) + substring(DB_USERLGI, 14, 1) +
         substring(DB_USERLGI, 1, 1) + substring(DB_USERLGI, 5, 1) +
         substring(DB_USERLGI, 9, 1) + substring(DB_USERLGI, 13, 1) +
         substring(DB_USERLGI, 17, 1) + substring(DB_USERLGI, 4, 1) +
         substring(DB_USERLGI, 8, 1)) = USR_ID))
		 USUARIO
, CASE WHEN DB_TM < '500' THEN D1_IDENTB6 ELSE D2_IDENTB6 END IDENT
FROM SDB010 SDB
LEFT JOIN SB1010 SB1 ON
B1_COD = DB_PRODUTO AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = SB1.B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
LEFT JOIN SF4010 SF4 ON
SF4.F4_CODIGO = SDB.DB_TM AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SF5010 SF5 ON
SF5.F5_CODIGO = SDB.DB_TM AND SF5.D_E_L_E_T_ <> '*'
LEFT JOIN #SD1_NFS SD1 ON
DB_FILIAL = D1_FILIAL AND DB_DOC = D1_DOC AND DB_TM < '500' AND DB_SERIE = D1_SERIE AND DB_CLIFOR = SD1.CLIFOR_COD AND DB_LOJA = SD1.CLIFOR_LOJA
LEFT JOIN #SD2_NFS SD2 ON
DB_FILIAL = D2_FILIAL AND DB_DOC = D2_DOC AND DB_TM >= '500' AND DB_SERIE = D2_SERIE AND DB_CLIFOR = SD2.CLIFOR_COD AND DB_LOJA = SD2.CLIFOR_LOJA

LEFT JOIN (SELECT D2_CF, (SELECT F4_TEXTO FROM SF4010 SF4 WHERE F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*') F4_TEXTO,
(SELECT F4_TIPO FROM SF4010 SF4 WHERE F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*') F4_TIPO,D2_TES,D2_PEDIDO,D2_FILIAL,D2_DOC,D2_COD,D2_IDENTB6, D2_NUMSEQ, D2_SERIE FROM SD2010 WHERE D_E_L_E_T_ <> '*') SD2_IDENT ON
DB_NUMSEQ = D2_NUMSEQ AND DB_DOC = SD2_IDENT.D2_DOC AND DB_SERIE = SD2_IDENT.D2_SERIE AND DB_PRODUTO = SD2_IDENT.D2_COD AND DB_TM >= '500' AND SD2_IDENT.D2_FILIAL = DB_FILIAL
LEFT JOIN (SELECT D1_CF, (SELECT F4_TEXTO FROM SF4010 SF4 WHERE F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*') F4_TEXTO,
(SELECT F4_TEXTO FROM SF4010 SF4 WHERE F4_CODIGO = D1_TES AND SF4.D_E_L_E_T_ <> '*') F4_TIPO,D1_TES,D1_PEDIDO,D1_FILIAL,D1_DOC,D1_COD,D1_IDENTB6, D1_NUMSEQ, D1_SERIE FROM SD1010 WHERE D_E_L_E_T_ <> '*') SD1_IDENT ON
DB_NUMSEQ = D1_NUMSEQ AND DB_DOC = SD1_IDENT.D1_DOC AND DB_SERIE = SD1_IDENT.D1_SERIE AND DB_PRODUTO = SD1_IDENT.D1_COD AND DB_TM < '500' AND SD1_IDENT.D1_FILIAL = DB_FILIAL

WHERE SDB.D_E_L_E_T_ <> '*'  AND B1_TIPO = 'PA' AND DB_ESTORNO <> 'S'
GROUP BY
	DB_DATA
,	DB_FILIAL
,	DB_DOC
,	DB_TM
,	DB_ORIGEM
,	SD1.CLIFOR_COD
,	SD2.CLIFOR_COD
,	DB_CLIFOR
,	SD1.CLIFOR_NOME 
,	SD2.CLIFOR_NOME
,	SD1.CLIFOR_NREDUZ 
,	SD2.CLIFOR_NREDUZ
,	DB_LOTECTL
,	DB_NUMSERI
,	B1_COD
,	B1_DESC
, SD1_IDENT.F4_TIPO
, SD2_IDENT.F4_TIPO
, SD1_IDENT.F4_TEXTO
, SD2_IDENT.F4_TEXTO
, SD1_IDENT.D1_IDENTB6
, SD2_IDENT.D2_IDENTB6
,	SDB.R_E_C_N_O_
,	DB_IDOPERA
,	DB_USERLGA 
,	DB_USERLGI

UNION ALL

SELECT
	'Z08' AS TABELA
,	Z08_DATA
,	Z08_FILORI
,	SUBSTRING(Z08_NF,1,9) NF
, Z08_TIPO
, Z08_ACT
, B1_COD
, B1_DESC
, Z08_CLIFOR
, Z08_NOMECF
, (SELECT A1_NREDUZ FROM SA1010 WHERE D_E_L_E_T_ <> '*' AND LEFT(Z08_CLIFOR,6) = A1_COD AND RIGHT(Z08_CLIFOR, 2) = A1_LOJA) NREDUZ
, Z07_LOTE
, right(Z08_ID,6) SERIAL
, CASE
		WHEN Z08_TIPO IN ('D', 'J', 'I') THEN 1
		WHEN Z08_TIPO IN ('M', 'S') THEN -1
		ELSE 0
	END QUANT
, Z08.R_E_C_N_O_
, Z08_ORDEM
, Z08_USER
, Z08_IDENT
FROM Z08010 Z08
LEFT JOIN Z07010 Z07 ON
Z07_ID = Z08_ID AND Z07.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
B1_COD = Z07_PROD AND SB1.D_E_L_E_T_ <> '*'
WHERE Z08.D_E_L_E_T_ <> '*'
