USE PUOBH2;
SELECT TOP 1 WITH TIES CTD_DESC01,D2_EMISSAO,B1_COD, D2_PRCVEN FROM SD2010 SD2
LEFT JOIN SF4010 SF4 ON
F4_CODIGO = D2_TES AND SF4.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 SB1 ON
B1_COD = D2_COD AND SB1.D_E_L_E_T_ <> '*'
LEFT JOIN CTD010 CTD ON
CTD_ITEM = B1_ITEMCC AND CTD.D_E_L_E_T_ <> '*'
WHERE SD2.D_E_L_E_T_ <> '*' AND F4_DUPLIC = 'S' AND D2_TIPO IN ('C','P','N','I')
ORDER BY ROW_NUMBER() OVER (PARTITION BY D2_COD ORDER BY D2_COD, D2_EMISSAO DESC)
